### ISSUE TITLE
Failed during restore, it deletes current catalog dataset without create a new one

### ISSUE THREAD

**Issue by t0ury** [Heavybullets8/heavy_script#156] opened 2024-03-25 12:42 UTC
Seems heavyscript delete the current 'myNas01/ix-applications/catalogs' dataset but did not create new one?

When restore a system backup
```
Starting restore, this will take a LONG time.
[0%] ...
[5%] Basic validation complete...
[15%] Stopped kubernetes...
[17%] Waiting for catalog sync jobs to complete...
Error: Failed to delete dataset: cannot destroy 'myNas01/ix-applications/k3s/kubelet': dataset is busy
Restore failed, exiting..
```
Scale:
```
 error: force
Apps have been partially initialized on 'myNas01' pool but it is missing 'myNas01/ix-applications/catalogs' datasets. Specify force to override this and let system re-initialize applications.```

Heavyscript:
[0%] ...
[5%] Basic validation complete...
[15%] Stopped kubernetes...
[17%] Waiting for catalog sync jobs to complete...
Error: Failed to delete dataset: cannot open 'myNas01/ix-applications/catalogs': dataset does not exist
Restore failed, exiting..

**Comment by heavybullets8** [comment] 2024-04-29 08:18
Unfortunately this is caused by ix's API. All heavyscript does is call the restore function that they provide. 
Closing this as unrelated

**Closed as completed by heavybullets8** 2024-04-29 08:18 UTC
