### ISSUE TITLE
An image used by a Scale app keeps being pruned

### ISSUE THREAD

**Issue by sfatula** [Heavybullets8/heavy_script#131] opened 2023-09-06 17:28 UTC
I have one app where heavyscript is removing the docker image but it is needed for an app. 

So, I load a docker image in scale using "Manage Docker Images -> Pull Image" as I do for all my containers. In this base, the repo is mine, I have modified the URL to hide it but the image name is repo.mydomain.com:5000/prowlarr/fatula. I have more than a dozen apps like this, and they all pull from the same repo. The image tag, perhaps the tag is somehow an issue with special characters, is 1.7.4.3769-ls28 maybe the dash somehow?

On the "Manage Docker Images" screen, I can now type prowl in the search box and sure enough, it's now there. 

Now I run via command line: /root/heavy_script/heavy_script.sh update -v

Now searching for the image shows prowlarr is missing. Trying to start the app fails as there is no image and I have it set to not re-pull (it requires authentication). 

Note, all my other apps do not disappear, just this one! 

Now the app won't start as it is missing the image. If I re-pull the image, the app then starts but the next run of heavyscript then removes it again. So, the next time a restart occurs of truenas, the app won't start as the image is missing again. It's only this image, all apps use the same repo.

**Comment by heavybullets8** [comment] 2023-09-06 17:35
What version of Truenas SCALE are you using?

**Comment by sfatula** [comment] 2023-09-06 17:40
Version:
TrueNAS-SCALE-22.12.3.3

**Comment by heavybullets8** [comment] 2023-09-06 18:03
Is the application stopped during the prune?

What update flags/Config options did you change?

**Comment by sfatula** [comment] 2023-09-06 18:20
No, the app is not stopped during prune, my comments were merely an example I manually did to test it (had just been noticing every restart, which is not often, prowlarr would never start due to missing the image). The flags/options are the same as on the other apps if you are speaking of "Launch Docker Image" options. These would be:

DNS: Internal DNS first
Port Forwarding: container 9696 to node port 19696, TCP
A hostpath for /config
Enabled webui portal for http 19696.

**Comment by heavybullets8** [comment] 2023-09-06 18:34
When you run the prune via heavyscript, all it's really doing under the hood is calling ix's prune function with this command:
```bash
cli -c 'app container config prune prune_options={"remove_unused_images": true, "remove_stopped_containers": true}'
```

You can take a peek at the simple prune function in the [heavyscript code here](https://github.com/Heavybullets8/heavy_script/blob/main/functions/prune/prune.sh).

To get to the bottom of this, I'd suggest running the command directly, without heavyscript, to see if the issue still persists:
```bash
cli -c 'app container config prune prune_options={"remove_unused_images": true, "remove_stopped_containers": true}'
```
or, since `remove_stopped_containers` will be gone in the next TrueNAS SCALE update, try:
```bash
cli -c 'app container config prune prune_options={"remove_unused_images": true}'
```

If the problem is still there, it'd be best to let the ix team know about it. Just head to: 
Truenas SCALE GUI > System Settings > General > File Ticket 

You can copy-paste what you've shared here for your issue report with them. If you want, you can mention you stumbled upon this while using heavyscript, or just stick to the direct command test.

**Comment by sfatula** [comment] 2023-09-06 22:22
So, I did the CLI command without remove_stopped and prowalrr image goes away. I filed a ticket. Thanks!

**Comment by heavybullets8** [comment] 2023-09-06 22:30
Perfect! I'll close this. Reach out if you need anything else. Thank you, and have a good day.

**Closed as completed by heavybullets8** 2023-09-06 22:30 UTC
