### ISSUE TITLE
Failure to update stopped app

### ISSUE THREAD

**Issue by m42j** [Heavybullets8/heavy_script#137] opened 2023-10-20 10:39 UTC
HeavyScript v2.4.1
TrueNAS-SCALE-22.12.4.2
Cron `bash /root/heavy_script/heavy_script.sh update --backup 7 --concurrent 10 --prune --rollback --include-major --self-update`
Application created from "Launch Docker Image".
Application stopped from Application "Stop"-button.

Original log part
```
ntfy
Updated
binwiederhier/ntfy:latest_2308.0.0
binwiederhier/ntfy:latest_2308.0.1
Error: Run Time(500) for ntfy has exceeded Timeout(500)
If this is a slow starting application, set a higher timeout with -t
Reverting update..
Rolled Back
Error: Application did not come up even after a rollback
Manual intervention is required
Stopping, then Abandoning
Stopped
```

(BTW, where does TrueNAS get those 2308.0.x version numbers from?)
[outputfile.txt](https://github.com/Heavybullets8/heavy_script/files/13053258/outputfile.txt)

**Comment by heavybullets8** [comment] 2023-10-20 19:56
Ive pushed a possible fix to [helm-start-cnpg](https://github.com/Heavybullets8/heavy_script/tree/helm-start-cnpg)
 Can you switch to this branch and let me know if that works?
 ```
 heavyscript git --branch
 ```
 Then choose `helm-start-cnpg` and attempt the update with the troublesome application again.

**Comment by heavybullets8** [comment] 2023-10-20 21:42
This fix is included in v2.5.0 and should fix your issue. If not please let me know. I will close this issue after a while, assuming the issue is fixed.

**Comment by heavybullets8** [comment] 2023-10-21 01:27
Also, 
```
latest_2308.0.0
```
Appears to be the helm chart version. While using the "Launch Docker Image" Button, you are essentially using an empty helm chart. The values you type into the GUI while filling out your config, you are "filling" in the helm chart. It is somewhat more complex than that, but that is a surface level explanation. 

Whenever Ix pushes changes to their empty chart, an update becomes available for the chart version, as was your case.

**Comment by m42j** [comment] 2023-10-21 06:12
The cron-job ran last night, heavyscript upgraded itself to 2.5.0 and the app upgrade also worked.
Thanks!
I upgraded TrueNAS to 22.12.4 and that caused all apps to be upgraded on next run so version coming from Ix helm chart makes sense.
Thanks again!

**Comment by heavybullets8** [comment] 2023-10-21 06:14
Great news!
Closing on that note. 
Also, thanks for providing logs, and all the version information. You make this very easy.

**Closed as completed by heavybullets8** 2023-10-21 06:14 UTC
